print('kopa paithon kopa')
print('kopa tusi kopa')
print('kopa rohim kopa')
print('now i am kopaiyinga')
print('do you want me to fuck')
print('i am wating for fuck you')
print("this is kopaiyanga")
print('paithon is not just wating for you its amazing language ')
print('paithon re dhore felcei , mama!!')
print(111)
print(555)
print(7.85)
print('paithon is my first choice ')