print('kopa paithon kopa')
print('Nengti tui saima ka dhore fel')
print('Ami tomake bhalobasi')
print('kopa johir kopa karon tor somoi valo')
print('kosto kor khalique tor somoi kharap karon tui jonmo decos amr moto kulanger sontan')
print('Allah please help me')
print('Allah please give me a path')
print('Hey one and only Allah ,please see me! a have no one who help me')
print('KOpa shanto kopa karon Allah help you IN sha Allah')
print('Hey shanto tui valo thakta caila kosto kor')
print('Poresron cara kono bal certa parbi na mathai rakhis')
print('Boisa thaika lakha tk er sonpno dakha bokami cara kicu na')
print('casta cara boro hoya possible na')
print('Ami tomake valobashi')
print('KOba saja kopa')
print('Allhahu akbar')
print('Kopa tusi kopa')
print('python is a programming language')
print('I love you')
print('I miss you')
print("I don't need anyone's help beacause I have Allah")
print(1110)
print(444)
print(6734)